name: Test shell scripts in one container
jobs:
  - id: test_alpine
    display_name: Alpine runner
    runner: alpine
    tasks:
      - id: correct_ls
        display_name: Correct script - save uname in file
        command: |
          echo start correct_ls
          uname -a >> $AGENT_TASKS_DIR/uname.txt
          echo end correct_ls
      - id: correct_env
        display_name: Correct script - env
        command: |
          echo start correct_env
          echo job artifacts IN dir: $AGENT_JOB_ARTIFACTS_IN_DIR
          echo job artifacts OUT dir: $AGENT_JOB_ARTIFACTS_OUT_DIR
          echo job tasks dir: $AGENT_TASKS_DIR
          echo scripts dir: $AGENT_SCRIPTS_DIR
          echo end correct_env
      - id: read_uname_file
        display_name: Read file from agent task dir and save to the artifacts
        command: |
          echo start read_uname_file
          cat $AGENT_TASKS_DIR/uname.txt
          mkdir $AGENT_JOB_ARTIFACTS_OUT_DIR/test
          echo 'lorem ipsum' >>  $AGENT_JOB_ARTIFACTS_OUT_DIR/test/lorem.txt
          cp $AGENT_TASKS_DIR/uname.txt $AGENT_JOB_ARTIFACTS_OUT_DIR/
          echo end read_uname_file
  - id: test_busybox
    display_name: Busybox runner
    runner: busybox
    tasks:
      - id: copy_incoming_artifacts
        display_name: Copy incoming artifacts
        command: |
          echo start copy_incoming_artifacts
          ls -la $AGENT_JOB_ARTIFACTS_IN_DIR/
          cp -r $AGENT_JOB_ARTIFACTS_IN_DIR/* $AGENT_TASKS_DIR/
          echo end copy_incoming_artifacts
      - id: read_uname_file
        display_name: Read uname file
        command: |
          echo start read_uname_file
          cat $AGENT_TASKS_DIR/uname.txt
          echo end
