// Package db contains the types for schema 'public'.
package db

// Code generated by xo. DO NOT EDIT.

import (
	"database/sql"
	"errors"

	"github.com/gofrs/uuid"
)

// Build represents a row from 'public.build'.
type Build struct {
	UID            uuid.UUID      `json:"uid"`             // uid
	RepositoryHash string         `json:"repository_hash"` // repository_hash
	CommitHash     string         `json:"commit_hash"`     // commit_hash
	PipelineJSON   string         `json:"pipeline_json"`   // pipeline_json
	Logs           sql.NullString `json:"logs"`            // logs
	ResultStatus   string         `json:"result_status"`   // result_status
	ArtifactsUID   uuid.UUID      `json:"artifacts_uid"`   // artifacts_uid
	CreatedAt      int64          `json:"created_at"`      // created_at
	FinishAt       sql.NullInt64  `json:"finish_at"`       // finish_at

	// xo fields
	_exists, _deleted bool
}

// Exists determines if the Build exists in the database.
func (b *Build) Exists() bool {
	return b._exists
}

// Deleted provides information if the Build has been deleted from the database.
func (b *Build) Deleted() bool {
	return b._deleted
}

// Insert inserts the Build to the database.
func (b *Build) Insert(db XODB) error {
	var err error

	// if already exist, bail
	if b._exists {
		return errors.New("insert failed: already exists")
	}

	// sql insert query, primary key must be provided
	const sqlstr = `INSERT INTO public.build (` +
		`uid, repository_hash, commit_hash, pipeline_json, logs, result_status, artifacts_uid, created_at, finish_at` +
		`) VALUES (` +
		`$1, $2, $3, $4, $5, $6, $7, $8, $9` +
		`)`

	// run query
	XOLog(sqlstr, b.UID, b.RepositoryHash, b.CommitHash, b.PipelineJSON, b.Logs, b.ResultStatus, b.ArtifactsUID, b.CreatedAt, b.FinishAt)
	err = db.QueryRow(sqlstr, b.UID, b.RepositoryHash, b.CommitHash, b.PipelineJSON, b.Logs, b.ResultStatus, b.ArtifactsUID, b.CreatedAt, b.FinishAt).Scan(&b.UID)
	if err != nil {
		return err
	}

	// set existence
	b._exists = true

	return nil
}

// Update updates the Build in the database.
func (b *Build) Update(db XODB) error {
	var err error

	// if doesn't exist, bail
	if !b._exists {
		return errors.New("update failed: does not exist")
	}

	// if deleted, bail
	if b._deleted {
		return errors.New("update failed: marked for deletion")
	}

	// sql query
	const sqlstr = `UPDATE public.build SET (` +
		`repository_hash, commit_hash, pipeline_json, logs, result_status, artifacts_uid, created_at, finish_at` +
		`) = ( ` +
		`$1, $2, $3, $4, $5, $6, $7, $8` +
		`) WHERE uid = $9`

	// run query
	XOLog(sqlstr, b.RepositoryHash, b.CommitHash, b.PipelineJSON, b.Logs, b.ResultStatus, b.ArtifactsUID, b.CreatedAt, b.FinishAt, b.UID)
	_, err = db.Exec(sqlstr, b.RepositoryHash, b.CommitHash, b.PipelineJSON, b.Logs, b.ResultStatus, b.ArtifactsUID, b.CreatedAt, b.FinishAt, b.UID)
	return err
}

// Save saves the Build to the database.
func (b *Build) Save(db XODB) error {
	if b.Exists() {
		return b.Update(db)
	}

	return b.Insert(db)
}

// Upsert performs an upsert for Build.
//
// NOTE: PostgreSQL 9.5+ only
func (b *Build) Upsert(db XODB) error {
	var err error

	// if already exist, bail
	if b._exists {
		return errors.New("insert failed: already exists")
	}

	// sql query
	const sqlstr = `INSERT INTO public.build (` +
		`uid, repository_hash, commit_hash, pipeline_json, logs, result_status, artifacts_uid, created_at, finish_at` +
		`) VALUES (` +
		`$1, $2, $3, $4, $5, $6, $7, $8, $9` +
		`) ON CONFLICT (uid) DO UPDATE SET (` +
		`uid, repository_hash, commit_hash, pipeline_json, logs, result_status, artifacts_uid, created_at, finish_at` +
		`) = (` +
		`EXCLUDED.uid, EXCLUDED.repository_hash, EXCLUDED.commit_hash, EXCLUDED.pipeline_json, EXCLUDED.logs, EXCLUDED.result_status, EXCLUDED.artifacts_uid, EXCLUDED.created_at, EXCLUDED.finish_at` +
		`)`

	// run query
	XOLog(sqlstr, b.UID, b.RepositoryHash, b.CommitHash, b.PipelineJSON, b.Logs, b.ResultStatus, b.ArtifactsUID, b.CreatedAt, b.FinishAt)
	_, err = db.Exec(sqlstr, b.UID, b.RepositoryHash, b.CommitHash, b.PipelineJSON, b.Logs, b.ResultStatus, b.ArtifactsUID, b.CreatedAt, b.FinishAt)
	if err != nil {
		return err
	}

	// set existence
	b._exists = true

	return nil
}

// Delete deletes the Build from the database.
func (b *Build) Delete(db XODB) error {
	var err error

	// if doesn't exist, bail
	if !b._exists {
		return nil
	}

	// if deleted, bail
	if b._deleted {
		return nil
	}

	// sql query
	const sqlstr = `DELETE FROM public.build WHERE uid = $1`

	// run query
	XOLog(sqlstr, b.UID)
	_, err = db.Exec(sqlstr, b.UID)
	if err != nil {
		return err
	}

	// set deleted
	b._deleted = true

	return nil
}

// BuildByUID retrieves a row from 'public.build' as a Build.
//
// Generated from index 'build_pkey'.
func BuildByUID(db XODB, uid uuid.UUID) (*Build, error) {
	var err error

	// sql query
	const sqlstr = `SELECT ` +
		`uid, repository_hash, commit_hash, pipeline_json, logs, result_status, artifacts_uid, created_at, finish_at ` +
		`FROM public.build ` +
		`WHERE uid = $1`

	// run query
	XOLog(sqlstr, uid)
	b := Build{
		_exists: true,
	}

	err = db.QueryRow(sqlstr, uid).Scan(&b.UID, &b.RepositoryHash, &b.CommitHash, &b.PipelineJSON, &b.Logs, &b.ResultStatus, &b.ArtifactsUID, &b.CreatedAt, &b.FinishAt)
	if err != nil {
		return nil, err
	}

	return &b, nil
}
