// Package db contains the types for schema 'public'.
package db

// Code generated by xo. DO NOT EDIT.

import (
	"errors"
)

// KvBuildLastCommit represents a row from 'public.kv_build_last_commit'.
type KvBuildLastCommit struct {
	ID              int    `json:"id"`                // id
	Key             string `json:"key"`               // key
	ValueHashCommit string `json:"value_hash_commit"` // value_hash_commit
	CreatedAt       int64  `json:"created_at"`        // created_at

	// xo fields
	_exists, _deleted bool
}

// Exists determines if the KvBuildLastCommit exists in the database.
func (kblc *KvBuildLastCommit) Exists() bool {
	return kblc._exists
}

// Deleted provides information if the KvBuildLastCommit has been deleted from the database.
func (kblc *KvBuildLastCommit) Deleted() bool {
	return kblc._deleted
}

// Insert inserts the KvBuildLastCommit to the database.
func (kblc *KvBuildLastCommit) Insert(db XODB) error {
	var err error

	// if already exist, bail
	if kblc._exists {
		return errors.New("insert failed: already exists")
	}

	// sql insert query, primary key provided by sequence
	const sqlstr = `INSERT INTO public.kv_build_last_commit (` +
		`key, value_hash_commit, created_at` +
		`) VALUES (` +
		`$1, $2, $3` +
		`) RETURNING id`

	// run query
	XOLog(sqlstr, kblc.Key, kblc.ValueHashCommit, kblc.CreatedAt)
	err = db.QueryRow(sqlstr, kblc.Key, kblc.ValueHashCommit, kblc.CreatedAt).Scan(&kblc.ID)
	if err != nil {
		return err
	}

	// set existence
	kblc._exists = true

	return nil
}

// Update updates the KvBuildLastCommit in the database.
func (kblc *KvBuildLastCommit) Update(db XODB) error {
	var err error

	// if doesn't exist, bail
	if !kblc._exists {
		return errors.New("update failed: does not exist")
	}

	// if deleted, bail
	if kblc._deleted {
		return errors.New("update failed: marked for deletion")
	}

	// sql query
	const sqlstr = `UPDATE public.kv_build_last_commit SET (` +
		`key, value_hash_commit, created_at` +
		`) = ( ` +
		`$1, $2, $3` +
		`) WHERE id = $4`

	// run query
	XOLog(sqlstr, kblc.Key, kblc.ValueHashCommit, kblc.CreatedAt, kblc.ID)
	_, err = db.Exec(sqlstr, kblc.Key, kblc.ValueHashCommit, kblc.CreatedAt, kblc.ID)
	return err
}

// Save saves the KvBuildLastCommit to the database.
func (kblc *KvBuildLastCommit) Save(db XODB) error {
	if kblc.Exists() {
		return kblc.Update(db)
	}

	return kblc.Insert(db)
}

// Upsert performs an upsert for KvBuildLastCommit.
//
// NOTE: PostgreSQL 9.5+ only
func (kblc *KvBuildLastCommit) Upsert(db XODB) error {
	var err error

	// if already exist, bail
	if kblc._exists {
		return errors.New("insert failed: already exists")
	}

	// sql query
	const sqlstr = `INSERT INTO public.kv_build_last_commit (` +
		`id, key, value_hash_commit, created_at` +
		`) VALUES (` +
		`$1, $2, $3, $4` +
		`) ON CONFLICT (id) DO UPDATE SET (` +
		`id, key, value_hash_commit, created_at` +
		`) = (` +
		`EXCLUDED.id, EXCLUDED.key, EXCLUDED.value_hash_commit, EXCLUDED.created_at` +
		`)`

	// run query
	XOLog(sqlstr, kblc.ID, kblc.Key, kblc.ValueHashCommit, kblc.CreatedAt)
	_, err = db.Exec(sqlstr, kblc.ID, kblc.Key, kblc.ValueHashCommit, kblc.CreatedAt)
	if err != nil {
		return err
	}

	// set existence
	kblc._exists = true

	return nil
}

// Delete deletes the KvBuildLastCommit from the database.
func (kblc *KvBuildLastCommit) Delete(db XODB) error {
	var err error

	// if doesn't exist, bail
	if !kblc._exists {
		return nil
	}

	// if deleted, bail
	if kblc._deleted {
		return nil
	}

	// sql query
	const sqlstr = `DELETE FROM public.kv_build_last_commit WHERE id = $1`

	// run query
	XOLog(sqlstr, kblc.ID)
	_, err = db.Exec(sqlstr, kblc.ID)
	if err != nil {
		return err
	}

	// set deleted
	kblc._deleted = true

	return nil
}

// KvBuildLastCommitByID retrieves a row from 'public.kv_build_last_commit' as a KvBuildLastCommit.
//
// Generated from index 'kv_build_last_commit_pkey'.
func KvBuildLastCommitByID(db XODB, id int) (*KvBuildLastCommit, error) {
	var err error

	// sql query
	const sqlstr = `SELECT ` +
		`id, key, value_hash_commit, created_at ` +
		`FROM public.kv_build_last_commit ` +
		`WHERE id = $1`

	// run query
	XOLog(sqlstr, id)
	kblc := KvBuildLastCommit{
		_exists: true,
	}

	err = db.QueryRow(sqlstr, id).Scan(&kblc.ID, &kblc.Key, &kblc.ValueHashCommit, &kblc.CreatedAt)
	if err != nil {
		return nil, err
	}

	return &kblc, nil
}
