// Package db contains the types for schema 'public'.
package db

// Code generated by xo. DO NOT EDIT.

import (
	"database/sql"
	"errors"

	"github.com/gofrs/uuid"
)

// Project represents a row from 'public.project'.
type Project struct {
	UID         uuid.UUID      `json:"uid"`         // uid
	Name        string         `json:"name"`        // name
	Description sql.NullString `json:"description"` // description
	CreatedAt   int64          `json:"created_at"`  // created_at

	// xo fields
	_exists, _deleted bool
}

// Exists determines if the Project exists in the database.
func (p *Project) Exists() bool {
	return p._exists
}

// Deleted provides information if the Project has been deleted from the database.
func (p *Project) Deleted() bool {
	return p._deleted
}

// Insert inserts the Project to the database.
func (p *Project) Insert(db XODB) error {
	var err error

	// if already exist, bail
	if p._exists {
		return errors.New("insert failed: already exists")
	}

	// sql insert query, primary key must be provided
	const sqlstr = `INSERT INTO public.project (` +
		`uid, name, description, created_at` +
		`) VALUES (` +
		`$1, $2, $3, $4` +
		`)`

	// run query
	XOLog(sqlstr, p.UID, p.Name, p.Description, p.CreatedAt)
	err = db.QueryRow(sqlstr, p.UID, p.Name, p.Description, p.CreatedAt).Scan(&p.UID)
	if err != nil {
		return err
	}

	// set existence
	p._exists = true

	return nil
}

// Update updates the Project in the database.
func (p *Project) Update(db XODB) error {
	var err error

	// if doesn't exist, bail
	if !p._exists {
		return errors.New("update failed: does not exist")
	}

	// if deleted, bail
	if p._deleted {
		return errors.New("update failed: marked for deletion")
	}

	// sql query
	const sqlstr = `UPDATE public.project SET (` +
		`name, description, created_at` +
		`) = ( ` +
		`$1, $2, $3` +
		`) WHERE uid = $4`

	// run query
	XOLog(sqlstr, p.Name, p.Description, p.CreatedAt, p.UID)
	_, err = db.Exec(sqlstr, p.Name, p.Description, p.CreatedAt, p.UID)
	return err
}

// Save saves the Project to the database.
func (p *Project) Save(db XODB) error {
	if p.Exists() {
		return p.Update(db)
	}

	return p.Insert(db)
}

// Upsert performs an upsert for Project.
//
// NOTE: PostgreSQL 9.5+ only
func (p *Project) Upsert(db XODB) error {
	var err error

	// if already exist, bail
	if p._exists {
		return errors.New("insert failed: already exists")
	}

	// sql query
	const sqlstr = `INSERT INTO public.project (` +
		`uid, name, description, created_at` +
		`) VALUES (` +
		`$1, $2, $3, $4` +
		`) ON CONFLICT (uid) DO UPDATE SET (` +
		`uid, name, description, created_at` +
		`) = (` +
		`EXCLUDED.uid, EXCLUDED.name, EXCLUDED.description, EXCLUDED.created_at` +
		`)`

	// run query
	XOLog(sqlstr, p.UID, p.Name, p.Description, p.CreatedAt)
	_, err = db.Exec(sqlstr, p.UID, p.Name, p.Description, p.CreatedAt)
	if err != nil {
		return err
	}

	// set existence
	p._exists = true

	return nil
}

// Delete deletes the Project from the database.
func (p *Project) Delete(db XODB) error {
	var err error

	// if doesn't exist, bail
	if !p._exists {
		return nil
	}

	// if deleted, bail
	if p._deleted {
		return nil
	}

	// sql query
	const sqlstr = `DELETE FROM public.project WHERE uid = $1`

	// run query
	XOLog(sqlstr, p.UID)
	_, err = db.Exec(sqlstr, p.UID)
	if err != nil {
		return err
	}

	// set deleted
	p._deleted = true

	return nil
}

// ProjectByUID retrieves a row from 'public.project' as a Project.
//
// Generated from index 'project_pkey'.
func ProjectByUID(db XODB, uid uuid.UUID) (*Project, error) {
	var err error

	// sql query
	const sqlstr = `SELECT ` +
		`uid, name, description, created_at ` +
		`FROM public.project ` +
		`WHERE uid = $1`

	// run query
	XOLog(sqlstr, uid)
	p := Project{
		_exists: true,
	}

	err = db.QueryRow(sqlstr, uid).Scan(&p.UID, &p.Name, &p.Description, &p.CreatedAt)
	if err != nil {
		return nil, err
	}

	return &p, nil
}
