// Package db contains the types for schema 'public'.
package db

// Code generated by xo. DO NOT EDIT.

import (
	"errors"

	"github.com/gofrs/uuid"
)

// Repository represents a row from 'public.repository'.
type Repository struct {
	RepoHash      string    `json:"repo_hash"`      // repo_hash
	RepositoryURL string    `json:"repository_url"` // repository_url
	DefaultBranch string    `json:"default_branch"` // default_branch
	Name          string    `json:"name"`           // name
	CreatedAt     int64     `json:"created_at"`     // created_at
	ProjectUID    uuid.UUID `json:"project_uid"`    // project_uid

	// xo fields
	_exists, _deleted bool
}

// Exists determines if the Repository exists in the database.
func (r *Repository) Exists() bool {
	return r._exists
}

// Deleted provides information if the Repository has been deleted from the database.
func (r *Repository) Deleted() bool {
	return r._deleted
}

// Insert inserts the Repository to the database.
func (r *Repository) Insert(db XODB) error {
	var err error

	// if already exist, bail
	if r._exists {
		return errors.New("insert failed: already exists")
	}

	// sql insert query, primary key must be provided
	const sqlstr = `INSERT INTO public.repository (` +
		`repo_hash, repository_url, default_branch, name, created_at, project_uid` +
		`) VALUES (` +
		`$1, $2, $3, $4, $5, $6` +
		`)`

	// run query
	XOLog(sqlstr, r.RepoHash, r.RepositoryURL, r.DefaultBranch, r.Name, r.CreatedAt, r.ProjectUID)
	err = db.QueryRow(sqlstr, r.RepoHash, r.RepositoryURL, r.DefaultBranch, r.Name, r.CreatedAt, r.ProjectUID).Scan(&r.RepoHash)
	if err != nil {
		return err
	}

	// set existence
	r._exists = true

	return nil
}

// Update updates the Repository in the database.
func (r *Repository) Update(db XODB) error {
	var err error

	// if doesn't exist, bail
	if !r._exists {
		return errors.New("update failed: does not exist")
	}

	// if deleted, bail
	if r._deleted {
		return errors.New("update failed: marked for deletion")
	}

	// sql query
	const sqlstr = `UPDATE public.repository SET (` +
		`repository_url, default_branch, name, created_at, project_uid` +
		`) = ( ` +
		`$1, $2, $3, $4, $5` +
		`) WHERE repo_hash = $6`

	// run query
	XOLog(sqlstr, r.RepositoryURL, r.DefaultBranch, r.Name, r.CreatedAt, r.ProjectUID, r.RepoHash)
	_, err = db.Exec(sqlstr, r.RepositoryURL, r.DefaultBranch, r.Name, r.CreatedAt, r.ProjectUID, r.RepoHash)
	return err
}

// Save saves the Repository to the database.
func (r *Repository) Save(db XODB) error {
	if r.Exists() {
		return r.Update(db)
	}

	return r.Insert(db)
}

// Upsert performs an upsert for Repository.
//
// NOTE: PostgreSQL 9.5+ only
func (r *Repository) Upsert(db XODB) error {
	var err error

	// if already exist, bail
	if r._exists {
		return errors.New("insert failed: already exists")
	}

	// sql query
	const sqlstr = `INSERT INTO public.repository (` +
		`repo_hash, repository_url, default_branch, name, created_at, project_uid` +
		`) VALUES (` +
		`$1, $2, $3, $4, $5, $6` +
		`) ON CONFLICT (repo_hash) DO UPDATE SET (` +
		`repo_hash, repository_url, default_branch, name, created_at, project_uid` +
		`) = (` +
		`EXCLUDED.repo_hash, EXCLUDED.repository_url, EXCLUDED.default_branch, EXCLUDED.name, EXCLUDED.created_at, EXCLUDED.project_uid` +
		`)`

	// run query
	XOLog(sqlstr, r.RepoHash, r.RepositoryURL, r.DefaultBranch, r.Name, r.CreatedAt, r.ProjectUID)
	_, err = db.Exec(sqlstr, r.RepoHash, r.RepositoryURL, r.DefaultBranch, r.Name, r.CreatedAt, r.ProjectUID)
	if err != nil {
		return err
	}

	// set existence
	r._exists = true

	return nil
}

// Delete deletes the Repository from the database.
func (r *Repository) Delete(db XODB) error {
	var err error

	// if doesn't exist, bail
	if !r._exists {
		return nil
	}

	// if deleted, bail
	if r._deleted {
		return nil
	}

	// sql query
	const sqlstr = `DELETE FROM public.repository WHERE repo_hash = $1`

	// run query
	XOLog(sqlstr, r.RepoHash)
	_, err = db.Exec(sqlstr, r.RepoHash)
	if err != nil {
		return err
	}

	// set deleted
	r._deleted = true

	return nil
}

// RepositoryByRepoHash retrieves a row from 'public.repository' as a Repository.
//
// Generated from index 'repository_pkey'.
func RepositoryByRepoHash(db XODB, repoHash string) (*Repository, error) {
	var err error

	// sql query
	const sqlstr = `SELECT ` +
		`repo_hash, repository_url, default_branch, name, created_at, project_uid ` +
		`FROM public.repository ` +
		`WHERE repo_hash = $1`

	// run query
	XOLog(sqlstr, repoHash)
	r := Repository{
		_exists: true,
	}

	err = db.QueryRow(sqlstr, repoHash).Scan(&r.RepoHash, &r.RepositoryURL, &r.DefaultBranch, &r.Name, &r.CreatedAt, &r.ProjectUID)
	if err != nil {
		return nil, err
	}

	return &r, nil
}
